
name: drone-env
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - pytorch-cuda=12.1
  - pip
  - pip:
      - ultralytics>=8.0.0
      - opencv-python
      - numpy
      - pandas
      - matplotlib
      - albumentations
      - pyyaml
      - tqdm
      - scikit-learn
      - filterpy
      - lapx
